# Github Workflow that build docker images using maven Fabrik IO
name: Docker CI/CD thought maven
run-name: "[tock: ${{ inputs.tock_version }}] Docker images build"

# Work in progress :
# -> Study external AND manual trigger with a set of specific versions for tock (and maybe other components)


on:
  workflow_dispatch:
    inputs:
      tock_version:
        description: "The version of tock released on maven central. Default to the version defined in the pom.xml"
        required: false
  push:
    branches:
      - github_actions_ci_cd_tests
  # TODO hanlde PR events

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install JAVA and maven toolchain
      - name: Setup Java and Maven using the same version as the docker
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '23' # Based on the version used in the docker images
      - name: Build docker images using maven (fabric8io)
        env:
          TOCK_VERSION: ${{ inputs.tock_version }} # Optionnal tock_version to override pom.xml's version
        run: |
          mvn package docker:build ${TOCK_VERSION:+-Dtock="$TOCK_VERSION"} \
            -pl "!llm-indexing-tools" # Ignore tock-llm-indexing-tools as it reference a local dependency
